# configuration options that were used in the github workflow
include_fragments = true
max_retries = 6
max_concurrency = 1

# excluding links to pull requests and issues is done for performance
exclude = [
  '^https://github.com/open-telemetry/opentelemetry-java-contrib/(issues|pull)/\\d+$',
]