max_retries = 6
max_concurrency = 1

# Check fragments in links
include_fragments = true

# excluding links to pull requests and issues is done for performance
exclude = [
  "^https://github.com/open-telemetry/opentelemetry-java-contrib/(issues|pull)/\\d+$",
]