name: Reusable - Check links

on:
  workflow_call:

permissions:
  contents: read

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Check links
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: ./.github/scripts/check-links.sh